# Generated by Django 4.2.7 on 2025-08-30 13:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('repository_url', models.URLField(max_length=500)),
                ('repository_name', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('tech_stack', models.JSONField(default=dict)),
                ('file_structure', models.JSONField(default=dict)),
                ('setup_instructions', models.TextField()),
                ('stars', models.IntegerField(default=0)),
                ('forks', models.IntegerField(default=0)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Repository Analysis',
                'verbose_name_plural': 'Repository Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('format', models.CharField(choices=[('md', 'Markdown'), ('txt', 'Text'), ('pdf', 'PDF'), ('docx', 'Word Document')], max_length=10)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='analyzer.repositoryanalysis')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('analysis', 'format')},
            },
        ),
    ]
