# Generated by Django 4.2.7 on 2025-08-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoryanalysis',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='repositoryanalysis',
            name='language',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
